### ISSUE TITLE
Undefined subroutine &main::GetItem Koha Unquarantine Script

### ISSUE THREAD

**Issue by jkgongora** [DSI-Universite-Rennes2/koha-unquarantine#1]
Error Koha versión 19.11.06

root @ ip-xx: / usr / share / koha / bin / cronjobs # perl unquarantine.pl 9 1

Undefined subroutine &main::GetItem called at unquarantine.pl line 36.

**Comment by gjoncour** [comment]
Hi,

We still use Koha 18.11 here and the old fashioned way to edit an item (using `C4::Items`) works. But `C4::Items::GetItem()` has been removed since 19.05. 
The last commit (540fe48457fa8bf0a1a1b679d8579b8260c55cfd) update it using `Koha::Item` (who is available since 3.22) instead. 

Thank you for reporting this issue.

**Comment by jkgongora** [comment]
Hi gjoncour:

Thank you.

All Ok.

Happy day.
